### ISSUE TITLE
Fix format / typo

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/hacktoberfest-project-list#12]
There is a little mistake 
super easy task

![grafik](https://user-images.githubusercontent.com/6397577/193423297-35e7dbc6-01cc-4c17-a06b-de4980dc888e.png)

**Comment by xoxo16** [comment]
pls assign this issue

**Comment by Gismo1337** [comment]
@xoxo16 done =) have fun!

**Comment by xoxo16** [comment]
can u tell more about the issue as i am new to open source

**Comment by Gismo1337** [comment]
@xoxo16 something like this you should ask before.
in the [showcase.md](https://github.com/Gismo1337/hacktoberfest-project-list/blob/master/posts/showcase.md) is an error.

**Comment by Gismo1337** [comment]
Got the information not to use hacktoberfest-accepted label. every repo with this label is auto registrated.
