### ISSUE TITLE
add more hacktoberfest projects to the showcase.md

### ISSUE THREAD

**Issue by Gismo1337** [Gismo1337/hacktoberfest-project-list#5]
List more active hacktoberfest repositories to the showcase.md

**Comment by clairecharles** [comment]
Hey @Gismo1337 can i work on this

**Comment by Gismo1337** [comment]
> Hey @Gismo1337 can i work on this

@clairecharles I assigned this to you. Sorry for the delay. I am busy today. Feel free to start anytime.
